import type { Course, Plugin, User, Lesson } from "@/lib/types";

/* ==================== 学习 ==================== */

export const cordisLessons: Lesson[] = [
  {
    id: "cordis-01",
    slug: "01-intro",
    index: 1,
    title: "摘要与引言：动态组合与两个维度",
    summary: "时间可组合性、空间可组合性到底是什么",
    duration: "20 分钟",
    status: "completed",
  },
  {
    id: "cordis-02",
    slug: "02-motivation",
    index: 2,
    title: "动机示例：VSCode 插件与 AI 智能体",
    summary: "为什么现在的软件做不到运行时卸载",
    duration: "15 分钟",
    status: "completed",
  },
  {
    id: "cordis-03",
    slug: "03-contributions-types",
    index: 3,
    title: "贡献回顾与类型判断 Γ ⊢ t : T",
    summary: "效应标注：类型不只记录返回值，还记录副作用",
    duration: "15 分钟",
    status: "completed",
  },
  {
    id: "cordis-04",
    slug: "04-monad",
    index: 4,
    title: "单子与代数效应：副作用装进盒子",
    summary: "Promise 就是单子：η 装值、flatMap 压平",
    duration: "25 分钟",
    status: "completed",
  },
  {
    id: "cordis-05",
    slug: "05-coeffect",
    index: 5,
    title: "余效应：计算需要环境给什么",
    summary: "效应问『我改了什么』，余效应问『我需要什么』",
    duration: "20 分钟",
    status: "in_progress",
  },
  {
    id: "cordis-06",
    slug: "06-revertible-effects",
    index: 6,
    title: "可回退效应：装得上去，拆得下来",
    summary: "每个上下文变换都配一个显式逆变换",
    duration: "30 分钟",
    status: "locked",
  },
  {
    id: "cordis-07",
    slug: "07-effect-composition",
    index: 7,
    title: "效应函数与组合：逆变换自动组合",
    summary: "⋄ 运算：复合效应的逆由组合自然得到",
    duration: "30 分钟",
    status: "locked",
  },
  {
    id: "cordis-08",
    slug: "08-reactive-coeffects",
    index: 8,
    title: "反应式余效应：依赖齐了自动启动",
    summary: "满足性、激活 / 停用 / 中性迁移分类",
    duration: "25 分钟",
    status: "locked",
  },
  {
    id: "cordis-09",
    slug: "09-lifecycle",
    index: 9,
    title: "组件生命周期：幂等、迭代、纪元、异步",
    summary: "惯性状态机：转换一旦开始就运行至完成",
    duration: "35 分钟",
    status: "locked",
  },
  {
    id: "cordis-10",
    slug: "10-context-paradigm",
    index: 10,
    title: "上下文范式：统一上下文类型 Γ∞",
    summary: "效应上下文与余效应上下文整合为一个实体",
    duration: "20 分钟",
    status: "locked",
  },
  {
    id: "cordis-11",
    slug: "11-core-library",
    index: 11,
    title: "Cordis 核心库：效应跟踪与余效应解析",
    summary: "ctx.effect、ctx.set、纤程与惯性状态机",
    duration: "30 分钟",
    status: "locked",
  },
  {
    id: "cordis-12",
    slug: "12-loader-koishi",
    index: 12,
    title: "组件加载器与 Koishi 案例",
    summary: "声明式配置、热模块替换、4000+ 插件生态",
    duration: "25 分钟",
    status: "locked",
  },
  {
    id: "cordis-13",
    slug: "13-discussion",
    index: 13,
    title: "讨论、相关工作与总结",
    summary: "服务多路复用、访问控制、版本管理",
    duration: "20 分钟",
    status: "locked",
  },
];

export const courses: Course[] = [
  {
    id: "cordis",
    slug: "cordis",
    title: "Cordis 论文精读：时空可组合性编程范式",
    description:
      "从零读懂《一种面向时空可组合性的编程范式》：不需要类型理论背景，用代码直觉理解可回退效应与反应式余效应。",
    tag: "论文精读",
    level: "入门",
    lessons: 13,
    progress: 4,
    duration: "约 5 小时",
    status: "进行中",
    featured: true,
    gradient: "from-brand-500 via-brand-600 to-accent-violet",
  },
  {
    id: "dsh-intro",
    slug: "dsh-intro",
    title: "DSH 入门指南：认识 DeepSeek Harness",
    description:
      "从工作区、任务、沙箱到技能系统，一小时建立 DSH 的整体心智模型，理解这个智能体开发平台的设计哲学。",
    tag: "入门课程",
    level: "入门",
    lessons: 10,
    progress: 2,
    duration: "约 3 小时",
    status: "进行中",
    featured: false,
    gradient: "from-accent-cyan to-brand-500",
  },
  {
    id: "agent-framework",
    slug: "agent-framework",
    title: "智能体框架实战：构建自演化智能体",
    description:
      "探索运行时智能体框架的架构：工具套件、权限沙箱、记忆系统与多智能体工作流，让智能体安全地自我修改。",
    tag: "进阶",
    level: "进阶",
    lessons: 12,
    progress: 0,
    duration: "约 6 小时",
    status: "未开始",
    featured: false,
    gradient: "from-brand-400 to-accent-cyan",
  },
  {
    id: "plugin-dev",
    slug: "plugin-dev",
    title: "插件开发速成：你的第一个 dsh 插件",
    description:
      "基于 Cordis 上下文范式写插件：声明余效应、使用 ctx.effect、实现热模块替换，20 分钟跑通完整流程。",
    tag: "实战",
    level: "入门",
    lessons: 8,
    progress: 0,
    duration: "约 2 小时",
    status: "未开始",
    featured: false,
    gradient: "from-accent-violet to-brand-500",
  },
];

/* ==================== 插件超市 ==================== */

export const plugins: Plugin[] = [
  {
    id: "translate",
    name: "@dshfind/translate",
    description: "AI 翻译服务：注入到任意上下文，多语言互译、术语表、批量翻译。",
    author: "shiyifan",
    installs: "12.4k",
    rating: 4.9,
    version: "2.1.0",
    tags: ["AI", "工具"],
    downloads: 12400,
  },
  {
    id: "database",
    name: "@dshfind/database",
    description: "数据库适配器：提供 SQLite / PostgreSQL / MySQL 统一余效应接口。",
    author: "weizhang",
    installs: "10.8k",
    rating: 4.8,
    version: "1.9.4",
    tags: ["存储", "核心"],
    downloads: 10800,
  },
  {
    id: "scheduler",
    name: "@dshfind/scheduler",
    description: "定时任务调度：cron 表达式、任务持久化、错过的任务自动补跑。",
    author: "tianyicui",
    installs: "8.2k",
    rating: 4.7,
    version: "3.0.1",
    tags: ["调度", "任务"],
    downloads: 8200,
  },
  {
    id: "analytics",
    name: "@dshfind/analytics",
    description: "数据分析看板：请求追踪、性能指标、插件使用统计的可视化仪表盘。",
    author: "koyuki",
    installs: "6.5k",
    rating: 4.6,
    version: "0.8.2",
    tags: ["监控", "可视化"],
    downloads: 6500,
  },
  {
    id: "auth",
    name: "@dshfind/auth",
    description: "访问控制与沙箱：基于能力的权限管理、拦截元数据、隔离域。",
    author: "shiki",
    installs: "5.9k",
    rating: 4.9,
    version: "1.2.0",
    tags: ["安全", "核心"],
    downloads: 5900,
  },
  {
    id: "notifier",
    name: "@dshfind/notifier",
    description: "通知服务：邮件、Webhook、IM 多渠道推送，依赖变更自动通知。",
    author: "nanami",
    installs: "4.3k",
    rating: 4.5,
    version: "0.5.7",
    tags: ["通知", "集成"],
    downloads: 4300,
  },
];

/* ==================== 用户排名 ==================== */

export const rankingUsers: User[] = [
  {
    id: "u1",
    name: "shiyifan",
    level: "Lv.12",
    points: 12840,
    contributions: 386,
    badges: ["论文精读官", "插件作者"],
    initial: "S",
    color: "from-brand-500 to-accent-cyan",
    trend: "up",
  },
  {
    id: "u2",
    name: "tianyicui",
    level: "Lv.11",
    points: 11290,
    contributions: 341,
    badges: ["Cordis 作者"],
    initial: "T",
    color: "from-accent-violet to-brand-500",
    trend: "up",
  },
  {
    id: "u3",
    name: "weizhang",
    level: "Lv.10",
    points: 9875,
    contributions: 298,
    badges: ["论文作者"],
    initial: "W",
    color: "from-accent-cyan to-accent-violet",
    trend: "down",
  },
  {
    id: "u4",
    name: "koyuki",
    level: "Lv.9",
    points: 8640,
    contributions: 254,
    badges: ["答疑达人"],
    initial: "K",
    color: "from-brand-400 to-brand-600",
    trend: "up",
  },
  {
    id: "u5",
    name: "shiki",
    level: "Lv.8",
    points: 7310,
    contributions: 209,
    badges: ["插件作者"],
    initial: "S",
    color: "from-accent-cyan to-brand-500",
    trend: "up",
  },
  {
    id: "u6",
    name: "nanami",
    level: "Lv.7",
    points: 6280,
    contributions: 177,
    badges: ["活跃用户"],
    initial: "N",
    color: "from-accent-violet to-brand-600",
    trend: "down",
  },
];
